base_url: https://generativelanguage.googleapis.com/v1beta/openai
api_key: AIzaSyC5AZzdt-... (your API key)
grid_size: 900
canvas_size: 900
max_seconds: 70

models:
  - id: gemini-3-flash-preview
  # - id: gemini-flash-lite-latest
  # - id: gemini-flash-latest
