base_url: https://generativelanguage.googleapis.com/v1beta/openai
api_key: AIzaSyC5AZzdt-XT2C_nqG28TbKOEqPLjBN6Jug
grid_size: 900
canvas_size: 900
max_seconds: 70

models:
  - id: gemini-3-flash-preview
  # - id: gemini-flash-lite-latest
  # - id: gemini-flash-latest
