base_url: https://openrouter.ai/api/v1
grid_size: 64
canvas_size: 256
max_seconds: 70
models:
  - google/gemini-3-flash-preview
options:
  - anthropic/claude-opus-4.1
  - anthropic/claude-opus-4.5
  - anthropic/claude-sonnet-4.5
  - bytedance-seed/seed-1.6
  - bytedance-seed/seed-1.6-flash
  - google/gemini-2.0-flash-001
  - google/gemini-2.0-flash-lite-001
  - google/gemini-2.5-flash
  - google/gemini-2.5-flash-lite
  - google/gemini-2.5-flash-lite-preview-09-2025
  - google/gemini-2.5-flash-preview-09-2025
  - google/gemini-2.5-pro
  - google/gemini-2.5-pro-preview
  - google/gemini-2.5-pro-preview-05-06
  - google/gemini-3-flash-preview
  - google/gemini-3-pro-preview
  - google/gemma-3-27b-it
  - google/gemma-3-27b-it:free
  - meta-llama/llama-4-maverick
  - meta-llama/llama-4-scout
  - mistralai/ministral-14b-2512
  - mistralai/ministral-3b-2512
  - mistralai/ministral-8b-2512
  - mistralai/mistral-large-2512
  - mistralai/mistral-medium-3
  - mistralai/mistral-medium-3.1
  - mistralai/mistral-small-3.1-24b-instruct
  - mistralai/mistral-small-3.1-24b-instruct:free
  - mistralai/mistral-small-3.2-24b-instruct
  - mistralai/pixtral-12b
  - mistralai/pixtral-large-2411
  - moonshotai/kimi-k2.5
  - openai/gpt-4-turbo
  - openai/gpt-4.1
  - openai/gpt-4.1-mini
  - openai/gpt-4.1-nano
  - openai/gpt-4o
  - openai/gpt-4o-2024-05-13
  - openai/gpt-4o-2024-08-06
  - openai/gpt-4o-2024-11-20
  - openai/gpt-4o-mini
  - openai/gpt-4o-mini-2024-07-18
  - openai/gpt-4o:extended
  - openai/gpt-5
  - openai/gpt-5-codex
  - openai/gpt-5-image
  - openai/gpt-5-image-mini
  - openai/gpt-5-mini
  - openai/gpt-5-nano
  - openai/gpt-5-pro
  - openai/gpt-5.1
  - openai/gpt-5.1-chat
  - openai/gpt-5.1-codex
  - openai/gpt-5.1-codex-max
  - openai/gpt-5.1-codex-mini
  - openai/gpt-5.2
  - openai/gpt-5.2-chat
  - openai/gpt-5.2-codex
  - openai/gpt-5.2-pro
  - openai/o1
  - openai/o3
  - openai/o3-deep-research
  - openai/o3-pro
  - openai/o4-mini
  - openai/o4-mini-deep-research
  - openai/o4-mini-high
  - qwen/qwen-vl-max
  - qwen/qwen3-vl-235b-a22b-instruct
  - qwen/qwen3-vl-235b-a22b-thinking
  - qwen/qwen3-vl-30b-a3b-instruct
  - qwen/qwen3-vl-30b-a3b-thinking
  - qwen/qwen3-vl-8b-instruct
  - qwen/qwen3-vl-8b-thinking
  - stepfun-ai/step3
  - x-ai/grok-4
  - x-ai/grok-4-fast
  - x-ai/grok-4.1-fast
  - z-ai/glm-4.5v
  - z-ai/glm-4.6v
